### PR TITLE
LeNet_Implementation Added

### PR DESCRIPTION
**Pull request by sarthakkalia**
Added the LeNet architecture, which was missing from the existing collection of CNN architectures.

### CODE REVIEW

**Comment by suzana-ilic** [comment]
@dkatsios

**Comment by dkatsios** [comment]
@sarthakkalia thank you for adding Le Net in the cnn architectures repo.
There are a few points that I want to mention regarding the code:
1. the name of the notebook file is `LeNet_implementation.ipynb.ipynb`. Can you remove the second `.ipynb`?
2. The cells within the notebook do not have incremental number for execution. For example, the first cell has execution number [2], and after [8] the next cell has number [30]. This affects also the names of the layers within the model. For example, the first layer in the summary is called `conv2d_12 (Conv2D)` when it should be `conv2d_1 (Conv2D)`.
3. The output dimensions from the summary do not match the dimensions mentioned in the paper. This is probably due to the initial reshaping to 28x28 instead of 32x32. Please make sure that the dimensions match in every layer.
4. I see that you also include code for training the model. There is no such part in the other implementations. However, it is ok to include it as long as it is following the methodology proposed in the original paper. So, if you choose to include the training method, please make sure to include the parts related to loss function, optimizer, learning rate, other hyperparameters, etc. from the paper to explain why you made the choices. 

Once again, thank you for the effort to develop the code and share it with the community.

**Comment by sarthakkalia** [comment]
**@dkatsios** 
Thank you for your feedback! I appreciate the detailed points you've raised. I'll make the necessary changes:

Correct the file name to remove the extra .ipynb.
Re-run the cells to ensure the execution numbers are incremental and update the layer names accordingly.
Adjust the input dimensions to match the original 32x32 size as mentioned in the paper, and ensure the output dimensions are accurate.
If I include the training section, I'll align it with the methodology from the original paper, including the relevant hyperparameters.
I'll make these changes and then submit a new pull request.

Thanks again for your guidance and support!

**Comment by sarthakkalia** [comment]
@dkatsios
@suzana-ilic 

I've made the changes as per your suggestions:

1. **File name**: The extra `.ipynb` has been removed.
2. **Cell execution numbers**: I re-ran the cells to ensure the execution numbers are incremental, which also updated the layer names in the model summary.
3. **Input dimensions**: I've adjusted the input dimensions to 32x32, as per the original LeNet paper, and verified that the output dimensions now match the paper.
4. **Training section**: I've decided to include the training section and have aligned it with the methodology proposed in the original paper, including the loss function, optimizer, learning rate, and other relevant hyperparameters.

I've submitted a new pull request with these updates. Please let me know if there are any further changes needed.

Thank you again for your feedback and support!

**Pull request merged**
